default: &default
  host: <%= ENV.fetch("INFLUX_HOST") { "localhost" } %>
  database: <%= ENV.fetch("INFLUX_NAME") { "botnbot" } %>
  username: <%= ENV.fetch("INFLUX_USERNAME") { "root" } %>
  password: <%= ENV.fetch("INFLUX_PASSWORD") { "" } %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
